name: rg-pipeline
trigger: none 
pool: pspool
steps: 
- task: TerraformInstaller@1
  displayName: task1-install
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: task2-init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/'
    backendServiceArm: 'psservice'
    backendAzureRmOverrideSubscriptionID: 'fc890557-6a78-4e91-9eac-5aff85b5fc09'
    backendAzureRmResourceGroupName: 'saurabhrg'
    backendAzureRmStorageAccountName: 'saurabhstg'
    backendAzureRmContainerName: 'saurabhcontainer'
    backendAzureRmKey: '.tfstate'
- task: TerraformTask@5
  displayName: task3-validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/'
- task: TerraformTask@5
  displayName: task 4-plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/'
    environmentServiceNameAzureRM: 'psservice'
    environmentAzureRmOverrideSubscriptionID: 'fc890557-6a78-4e91-9eac-5aff85b5fc09'
- task: TerraformTask@5
  displayName: task 5-apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/'
    environmentServiceNameAzureRM: 'psservice'
    environmentAzureRmOverrideSubscriptionID: 'fc890557-6a78-4e91-9eac-5aff85b5fc09'

- task: TerraformTask@5
  displayName: task 6-show
  inputs:
    provider: 'azurerm'
    command: 'show'
    outputTo: 'console'
    outputFormat: 'default'
    environmentServiceNameAzureRM: 'psservice'
    environmentAzureRmOverrideSubscriptionID: 'fc890557-6a78-4e91-9eac-5aff85b5fc09'